"""
EnneadTab for Rhino -- install/uninstall core logic.

Framework-agnostic business logic shared by the modern guided wizards
EnneadTab_For_Rhino_Installer.py and EnneadTab_For_Rhino_UnInstaller.py.
No Tk here -- every user-facing message goes through a `log` callback so the
same code drives the wizard's progress pane AND a plain console.

Replaces the legacy "drag EnneadTab_For_Rhino_Installer.rui onto Rhino" flow:
this launches Rhino headlessly (Rhino.exe /runscript=...) and runs a tiny
bootstrap script INSIDE that Rhino session which calls the already-shipped
EnneadTab.RHINO.RHINO_RUI helpers (rs.OpenToolbarCollection / AddStartupScript,
and their new close_rui / remove_startup_script counterparts) -- the same
calls the "Self Repair" / "Get Latest" buttons already make from inside a
running session, just triggered from outside instead of by hand.

IMPORTANT: this runs inside a *windowed* (--noconsole) PyInstaller exe, where
sys.stdout is None. Never call bare print() on a hot path -- use self.log().
"""

from __future__ import annotations

import ctypes
import json
import os
import re
import shutil
import subprocess
import threading
import time
import winreg
from ctypes import wintypes
from datetime import datetime
from typing import Callable, Optional

import psutil

import _Exe_Util


def safe_print(msg: str) -> None:
    """print() that never raises when stdout is None (windowed exe)."""
    try:
        print(msg)
    except Exception:
        pass


# Staged under WINDOW_TEMP_FOLDER (C:\\temp\\EnneadTab_Dump) deliberately --
# that path has no spaces. Rhino's /runscript= argument mis-parses a quoted
# path WITH spaces into the wrong argv token (confirmed empirically 2026-09-08:
# it opens the script file as a *document* instead of running it, producing a
# "File type not supported by Rhinoceros" dialog no automated caller would see
# or dismiss). Keeping every staged path space-free sidesteps the whole class
# of bug rather than trying to get the quoting exactly right.
BOOTSTRAP_TEMPLATE = '''# Auto-generated by EnneadTab_For_Rhino_Installer -- safe to delete.
import sys, json
sys.path.append(r"{lib_path}")
status = {{"ok": False, "error": None, "verified": None, "toolbars": None}}
try:
    import rhinoscriptsyntax as rs  # noqa
    from EnneadTab.RHINO import RHINO_RUI
    _required = ("update_my_rui", "add_startup_script") if {is_installing} else ("close_rui", "remove_startup_script")
    _missing = [n for n in _required if not hasattr(RHINO_RUI, n)]
    if _missing:
        raise AttributeError("EnneadTab lib is stale/incomplete (missing: " + ", ".join(_missing) + "). Update EnneadTab, then retry.")
    if {is_installing}:
        RHINO_RUI.update_my_rui()
        RHINO_RUI.add_startup_script()
    else:
        RHINO_RUI.close_rui()
        RHINO_RUI.remove_startup_script()
    # Verify the operation actually took effect in Rhino's LIVE toolbar state
    # rather than trusting that the calls merely returned without raising --
    # run() used to report success purely from "no exception", so a silent
    # no-op (e.g. a collection that never opened) still read as success (#5975).
    # NOTE: this confirms the in-session result, not disk persistence; a robust
    # persist-before-terminate guarantee needs the graceful-exit root fix and is
    # tracked separately. A mid-session "_-Toolbar _SaveAll" flush was tried and
    # rejected -- it hangs the headless bootstrap waiting on command prompts.
    _tb = [n for n in (rs.ToolbarCollectionNames() or []) if "enneadtab" in n.lower()]
    status["toolbars"] = _tb
    status["verified"] = bool(_tb) if {is_installing} else (len(_tb) == 0)
    status["ok"] = bool(status["verified"])
    if not status["ok"]:
        status["error"] = "operation ran but on-Rhino verification failed (enneadtab toolbars present: " + repr(_tb) + ")"
except Exception as e:
    status["error"] = str(e)
with open(r"{status_path}", "w") as f:
    json.dump(status, f)
'''


# The RHINO_RUI helpers the bootstrap calls. A lib missing any of these is
# stale/incomplete (e.g. a dev checkout parked on a branch predating the
# installer's helpers, #5971) -- find_lib_path validates against this and falls
# back to the published EA_Dist copy rather than launching Rhino only to hit a
# bare AttributeError. Keep in sync with BOOTSTRAP_TEMPLATE's call list above.
REQUIRED_RUI_HELPERS = ("update_my_rui", "add_startup_script", "close_rui", "remove_startup_script")

_user32 = ctypes.windll.user32
_EnumWindowsProc = ctypes.WINFUNCTYPE(wintypes.BOOL, wintypes.HWND, wintypes.LPARAM)


def _hide_windows_for_pid(pid: int) -> None:
    """Hide every top-level window belonging to `pid`, visible or not.

    `subprocess.STARTUPINFO(dwFlags=STARTF_USESHOWWINDOW, wShowWindow=SW_HIDE)`
    (used when launching Rhino below) only hides the FIRST window Rhino
    creates at startup -- confirmed live (2026-09-08) that it suppresses the
    main "Untitled" document window, but a separate "Update Available"
    notification Rhino throws up on its own still renders visible. This
    sweep is the general-purpose catch-all: call it on a short poll loop for
    the life of the bootstrap run so ANY window Rhino creates (an update
    check, a license prompt, a crash reporter) gets hidden the moment it
    appears, not just the one STARTUPINFO covers.
    """
    def callback(hwnd, lparam):
        found_pid = wintypes.DWORD()
        _user32.GetWindowThreadProcessId(hwnd, ctypes.byref(found_pid))
        if found_pid.value == pid:
            _user32.ShowWindow(hwnd, 0)  # SW_HIDE
        return True

    _user32.EnumWindows(_EnumWindowsProc(callback), 0)


def _run_window_hider(pid: int, stop_event: threading.Event) -> None:
    while not stop_event.is_set():
        _hide_windows_for_pid(pid)
        stop_event.wait(0.3)


class EnneadTabRhinoInstallationManager:
    """Handle EnneadTab for Rhino attach (install) / detach (uninstall).

    No .rui drag-and-drop: an external Rhino process is launched with
    `/runscript=` to run the bootstrap script above, which does the same
    `rs.OpenToolbarCollection` / `AddStartupScript` calls a user would
    otherwise trigger by hand (drag the .rui, then click Self Repair).
    """

    def __init__(
        self,
        is_installing: bool = True,
        log: Optional[Callable[[str], None]] = None,
    ):
        self.is_installing = is_installing
        self.log = log or safe_print
        self.start_time_iso = None
        self._lib_path = None
        self._rhino_exe = None

    # ------------------------------------------------------------------
    # host / prerequisite checks
    # ------------------------------------------------------------------
    def check_rhino_running(self) -> bool:
        """True only if the Rhino app itself (Rhino.exe) is running."""
        for process in psutil.process_iter(['pid', 'name']):
            try:
                name = (process.info.get('name') or '').lower()
            except Exception:
                continue
            if name == 'rhino.exe':
                return True
        return False

    def find_rhino_exe(self) -> Optional[str]:
        """Locate Rhino.exe via the McNeel registry key (cached).

        Tries Rhino 8 first, then 7 -- HKLM\\SOFTWARE\\McNeel\\Rhinoceros\\<ver>\\Install
        is the same key Rhino's own installer writes, so this does not
        depend on Rhino being on PATH or living at a guessed Program Files
        path (verified live on this machine 2026-09-08: version 8.30.26103.11001).
        """
        if self._rhino_exe is not None:
            return self._rhino_exe

        for version in ("8.0", "7.0"):
            key_path = r"SOFTWARE\McNeel\Rhinoceros\{}\Install".format(version)
            try:
                with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, key_path) as key:
                    exe_path, _ = winreg.QueryValueEx(key, "ExePath")
                if os.path.exists(exe_path):
                    self.log("Found Rhino {}: {}".format(version, exe_path))
                    self._rhino_exe = exe_path
                    return exe_path
            except FileNotFoundError:
                continue
            except OSError:
                continue

        self.log("Error: Rhino not found (checked registry for 8.0 and 7.0). Install Rhino first.")
        return None

    @staticmethod
    def _lib_has_required_helpers(lib_path: str) -> bool:
        """True if <lib>/EnneadTab/RHINO/RHINO_RUI.py defines every helper the
        bootstrap needs. Checked by SOURCE inspection, not import: RHINO_RUI
        imports rhinoscriptsyntax, which only exists inside Rhino, so it cannot
        be imported from this CPython installer process.
        """
        rui = os.path.join(lib_path, "EnneadTab", "RHINO", "RHINO_RUI.py")
        try:
            with open(rui, "r", encoding="utf-8", errors="replace") as f:
                src = f.read()
        except Exception:
            return False
        return all("def {}(".format(fn) in src for fn in REQUIRED_RUI_HELPERS)

    def find_lib_path(self) -> Optional[str]:
        """Locate a VALID EnneadTab Apps/lib folder (cached).

        Tries candidates in order and returns the first whose RHINO_RUI has the
        helpers the bootstrap calls: (1) find_main_repo() -- honours a local
        checkout on a dev box; (2) the published EA_Dist copy -- what a real
        user has. find_main_repo picks a checkout by NAME only, so a dev machine
        parked on a stale branch would otherwise feed the bootstrap a lib
        missing close_rui/etc and fail with a bare AttributeError (#5971).
        """
        if self._lib_path is not None:
            return self._lib_path

        self.log("Looking for EnneadTab OS...")
        candidates = []
        for cand in (os.path.join(_Exe_Util.find_main_repo(), "Apps", "lib"),
                     _Exe_Util.CORE_LIB_FOLDER):
            if cand not in candidates:
                candidates.append(cand)

        for lib_path in candidates:
            if not os.path.exists(lib_path):
                continue
            if not self._lib_has_required_helpers(lib_path):
                self.log("Skipping stale/incomplete EnneadTab lib (missing installer helpers): {}".format(lib_path))
                continue
            self.log("Found lib path: {}".format(lib_path))
            self._lib_path = lib_path
            return lib_path

        self.log("Error: no EnneadTab lib with the required installer helpers found. "
                 "Checked: {}. Update EnneadTab, then retry.".format(", ".join(candidates) or "none"))
        return None

    # ------------------------------------------------------------------
    # bootstrap runner
    # ------------------------------------------------------------------
    def _run_bootstrap(self) -> bool:
        rhino_exe = self.find_rhino_exe()
        lib_path = self.find_lib_path()
        if not rhino_exe or not lib_path:
            return False

        status_path = os.path.join(_Exe_Util.WINDOW_TEMP_FOLDER, "rhino_installer_bootstrap_status.json")
        bootstrap_path = os.path.join(_Exe_Util.WINDOW_TEMP_FOLDER, "rhino_installer_bootstrap.py")
        if os.path.exists(status_path):
            os.remove(status_path)

        with open(bootstrap_path, "w") as f:
            f.write(BOOTSTRAP_TEMPLATE.format(
                lib_path=lib_path,
                status_path=status_path,
                is_installing=self.is_installing,
            ))

        macro = "-_RunPythonScript {} -_Exit".format(bootstrap_path)
        self.log("Launching Rhino to {} the EnneadTab toolbar (no drag-and-drop needed)...".format(
            "attach" if self.is_installing else "detach"))
        # subprocess.Popen(list) quotes each argv element itself
        # (list2cmdline), and it wraps the WHOLE token in quotes starting
        # before "/runscript=" itself whenever the value contains a space.
        # That is argv-equivalent to quoting only the part after "=" -- but
        # Rhino's own /runscript= handling is NOT plain CommandLineToArgvW;
        # it apparently does its own parsing that only works when the quote
        # starts right after "=", not at the very front of the token.
        # Confirmed live (2026-09-08): a hand-built PowerShell command line
        # with `/runscript="..."` (quote after "=") worked; the byte-identical
        # POSIX-argv-equivalent `"/runscript=..."` (quote wraps the "/runscript="
        # prefix too, which is exactly what list2cmdline produces for this
        # value) made Rhino open a blank Untitled document and silently never
        # run the bootstrap script -- no error, no exception, nothing.
        # So: build the exact command-line string by hand instead of trusting
        # list2cmdline, and pass it as a single string (Popen uses a string
        # arg as the literal Windows command line, with NO further escaping).
        cmd = '"{}" /nosplash /runscript="{}"'.format(rhino_exe, macro)
        # Hide the window at launch (STARTUPINFO hint) -- this alone
        # suppresses the main "Untitled" document window (confirmed live
        # 2026-09-08), so the user never sees a Rhino UI appear at all for
        # what is otherwise identical to the visible flow above.
        startupinfo = subprocess.STARTUPINFO()
        startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
        startupinfo.wShowWindow = 0  # SW_HIDE
        proc = subprocess.Popen(cmd, startupinfo=startupinfo)

        # STARTUPINFO's hint only covers the first window Rhino creates.
        # A separate notification (e.g. Rhino's own "Update Available" check)
        # can still render visible on its own -- confirmed live 2026-09-08.
        # Run the general-purpose hide-sweep for the life of this call so
        # anything else Rhino tries to show gets hidden the moment it
        # appears too.
        hider_stop = threading.Event()
        hider_thread = threading.Thread(
            target=_run_window_hider, args=(proc.pid, hider_stop), daemon=True,
        )
        hider_thread.start()

        ok = False
        deadline = time.time() + 60
        while time.time() < deadline:
            if os.path.exists(status_path):
                try:
                    with open(status_path) as f:
                        result = json.load(f)
                except Exception:
                    result = {}
                ok = bool(result.get("ok"))
                if not ok and result.get("error"):
                    self.log("Rhino-side error: {}".format(result["error"]))
                break
            time.sleep(1)
        else:
            self.log("Timed out waiting for Rhino to finish (60s).")

        # -_Exit does not always tear the process down promptly -- confirmed
        # empirically (2026-09-08): EnneadTab's own startup hooks (MCP server
        # thread, InfraWatch registration) can outlive the closed main window.
        # Give it a grace period, then reclaim only THIS PID -- never another
        # Rhino session the user may have open.
        try:
            proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            try:
                psutil.Process(proc.pid).terminate()
            except Exception:
                pass
        finally:
            hider_stop.set()

        for path in (bootstrap_path, status_path):
            try:
                os.remove(path)
            except Exception:
                pass

        return ok

    # ------------------------------------------------------------------
    # Rhino 8 workspace persistence (containers.xml)
    # ------------------------------------------------------------------
    def _update_rhino8_containers_xml(self) -> bool:
        """Register or unregister EnneadTab Modern RUI in Rhino 8 containers.xml.

        Rhino 8 changed toolbar persistence: rs.OpenToolbarCollection only affects the
        live session, and does not persist across restarts unless registered in
        %APPDATA%/McNeel/Rhinoceros/8.0/settings/Scheme__*/containers.xml under <files>.
        Directly updating this file guarantees persistence without needing headless Rhino.
        """
        dump_folder = _Exe_Util.DUMP_FOLDER
        if not os.path.exists(dump_folder):
            try:
                os.makedirs(dump_folder)
            except Exception:
                pass

        rui_filename = "{}_For_Rhino_Modern.rui".format(_Exe_Util.PLUGIN_NAME)
        target_rui_path = os.path.join(dump_folder, rui_filename)

        if self.is_installing:
            main_repo = _Exe_Util.find_main_repo()
            candidates = [
                os.path.join(main_repo, "Apps", "_rhino", rui_filename),
                os.path.join(_Exe_Util.DIST_FOLDER, "Apps", "_rhino", rui_filename),
            ]
            for cand in candidates:
                if os.path.isfile(cand):
                    try:
                        shutil.copy2(cand, target_rui_path)
                        self.log("Staged RUI: {}".format(target_rui_path))
                    except Exception as e:
                        self.log("(RUI copy warning: {})".format(e))
                    break

        appdata = os.environ.get("APPDATA")
        if not appdata:
            return False

        rhino8_settings_dir = os.path.join(appdata, "McNeel", "Rhinoceros", "8.0", "settings")
        if not os.path.isdir(rhino8_settings_dir):
            return False

        rui_guid = "9d3c8a78-27a1-4c03-b74d-508554dcef36"
        plugin_guid = "02bf604d-799c-4cc2-830e-8d72f21b14b7"
        entry_line = '    <file_name guid="{}" plug_in_guid="{}" source="File">{}</file_name>'.format(
            rui_guid, plugin_guid, target_rui_path
        )

        modified_any = False
        for item in os.listdir(rhino8_settings_dir):
            scheme_dir = os.path.join(rhino8_settings_dir, item)
            if not os.path.isdir(scheme_dir) or not item.startswith("Scheme__"):
                continue
            xml_path = os.path.join(scheme_dir, "containers.xml")
            if not os.path.isfile(xml_path):
                continue

            try:
                with open(xml_path, "r", encoding="utf-8-sig") as f:
                    content = f.read()
            except Exception:
                try:
                    with open(xml_path, "r") as f:
                        content = f.read()
                except Exception:
                    continue

            has_entry = (target_rui_path.lower() in content.lower()) or (rui_guid.lower() in content.lower())

            if self.is_installing:
                if has_entry:
                    self.log("Rhino 8 workspace ({}) already links EnneadTab RUI.".format(item))
                    modified_any = True
                    continue
                if "<files>" in content and "</files>" in content:
                    content = content.replace("  <files>\n", "  <files>\n{}\n".format(entry_line), 1)
                elif "<files/>" in content:
                    content = content.replace("<files/>", "<files>\n{}\n  </files>".format(entry_line), 1)
                else:
                    files_block = "  <!--Open RUI files-->\n  <files>\n{}\n  </files>\n".format(entry_line)
                    if "<!--Plug-in associated files-->" in content:
                        content = content.replace("  <!--Plug-in associated files-->", files_block + "  <!--Plug-in associated files-->", 1)
                    elif "<plug_in_files>" in content:
                        content = content.replace("  <plug_in_files>", files_block + "  <plug_in_files>", 1)
                    elif "<dock_bars" in content:
                        content = content.replace("  <dock_bars", files_block + "  <dock_bars", 1)
                    else:
                        idx = content.find("</name>")
                        if idx != -1:
                            insert_pos = idx + len("</name>\n")
                            content = content[:insert_pos] + files_block + content[insert_pos:]
                        else:
                            continue
            else:
                if not has_entry:
                    modified_any = True
                    continue
                lines = content.splitlines(True)
                new_lines = [l for l in lines if (rui_guid.lower() not in l.lower()) and (target_rui_path.lower() not in l.lower()) and (rui_filename.lower() not in l.lower())]
                content = "".join(new_lines)
                content = re.sub(r"[ \t]*<!--Open RUI files-->\s*<files>\s*</files>\s*", "", content)
                content = re.sub(r"[ \t]*<files>\s*</files>\s*", "", content)

            try:
                bak_path = xml_path + ".bak"
                shutil.copy2(xml_path, bak_path)
                with open(xml_path, "w", encoding="utf-8-sig") as f:
                    f.write(content)
                self.log("Updated Rhino 8 toolbar layout in {}/containers.xml".format(item))
                modified_any = True
            except Exception as e:
                self.log("Failed to update {}: {}".format(xml_path, e))

        return modified_any

    # ------------------------------------------------------------------
    # status file (monitored by other processes)
    # ------------------------------------------------------------------
    def _update_status(self, status: str, details: str, end_time: Optional[str] = None) -> None:
        payload = {
            "status": status,
            "details": details,
            "start_time": self.start_time_iso,
            "end_time": end_time,
        }
        logger = "rhino_installer_status" if self.is_installing else "rhino_uninstaller_status"
        try:
            _Exe_Util.set_data(payload, logger)
        except Exception as e:
            self.log("(status write skipped: {})".format(e))

    # ------------------------------------------------------------------
    # native Windows toast on completion
    # ------------------------------------------------------------------
    def _notify_result(self, ok: bool, verb: str) -> None:
        """Fire a native Windows toast so success/failure is visible even if
        the user isn't looking at the wizard window -- important now that
        the whole flow runs headless (no Rhino window ever appears as its
        own visual confirmation). Reuses EnneadTab.NOTIFICATION.window_msg,
        the library's existing toast helper (win10toast if available, else a
        pure-ctypes Shell_NotifyIcon fallback with no extra dependency).
        Best-effort: a notification failure must never affect the actual
        install/uninstall result.
        """
        try:
            lib_path = self.find_lib_path()
            if not lib_path:
                return
            import sys
            if lib_path not in sys.path:
                sys.path.append(lib_path)
            from EnneadTab import NOTIFICATION

            title = "EnneadTab for Rhino"
            if ok:
                message = ("Installed -- open Rhino and look for the EnneadTab toolbar."
                           if self.is_installing else "Uninstalled -- EnneadTab is detached from Rhino.")
                image = "info"
            else:
                message = "{} failed. Open the installer window for details.".format(verb.capitalize())
                image = "error"
            NOTIFICATION.window_msg(title=title, message=message, image=image, duration=8)
        except Exception as e:
            self.log("(toast notification skipped: {})".format(e))

    # ------------------------------------------------------------------
    # orchestrator
    # ------------------------------------------------------------------
    def run(self) -> bool:
        """Attach (install) or detach (uninstall). Returns True on success."""
        self.start_time_iso = datetime.now().isoformat()
        verb = "install" if self.is_installing else "uninstall"

        if self.check_rhino_running():
            self.log("Rhino is currently running. Please close it before continuing, then retry.")
            self._update_status("failed", "Rhino was running", datetime.now().isoformat())
            self._notify_result(False, verb)
            return False

        self._update_status("running", "Starting EnneadTab for Rhino {}".format(verb))

        ok = self._run_bootstrap()

        # Update Rhino 8 containers.xml directly (Option A persistence fix).
        # In Rhino 8, rs.OpenToolbarCollection during bootstrap only loads the RUI in-memory
        # for that session and is not persisted. Writing to containers.xml guarantees persistence.
        try:
            r8_ok = self._update_rhino8_containers_xml()
            if r8_ok:
                ok = True
        except Exception as e:
            self.log("(Rhino 8 containers.xml update warning: {})".format(e))

        if ok:
            self._update_status(
                "success", "EnneadTab for Rhino {} completed successfully".format(verb),
                datetime.now().isoformat(),
            )
            if self.is_installing:
                self.log("Done. Open Rhino and look for the EnneadTab toolbar/tab.")
            else:
                self.log("EnneadTab has been detached from Rhino. You can close this window.")
        else:
            self._update_status("failed", "{} failed".format(verb), datetime.now().isoformat())
            self.log("{} did not complete. Review the log above, then retry.".format(verb.capitalize()))

        self._notify_result(ok, verb)
        return ok
